build:
  stage: build
  only:
    - develop
  script:
    - docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/eredinbg/soundwisecms_web:latest .
    - docker push registry.gitlab.com/eredinbg/soundwisecms_web:latest

deploy:
  stage: deploy
  only:
    - develop
  script:
    - cp docker-compose.yml /home/soundwise/docker-compose.yml
    - sudo GITLAB_USERNAME=$GITLAB_USERNAME GITLAB_PASSWORD=$GITLAB_PASSWORD su soundwise
    - sudo chmod +x on_behalf.sh
    - sudo ./on_behalf.sh soundwise "docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com"
    - sudo ./on_behalf.sh soundwise "docker-compose -f /home/soundwise/docker-compose.yml pull && docker-compose -f /home/soundwise/docker-compose.yml up -d"
