build:
  stage: build
  only:
    - develop
  script:
    - docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/eredinbg/soundwisecms_web:latest .
    - docker push registry.gitlab.com/eredinbg/soundwisecms_web:latest

deploy:
  stage: deploy
  only:
    - develop
  script:
    - sudo su -p soundwise
    - cp docker-compose.yml ~/docker-compose.yml
    - cd
    - docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com
      && docker-compose pull
      && docker-compose up -d