build:
  stage: build
  only:
    - develop
  script:
    - docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/eredinbg/soundwisecms_web:latest .
    - docker push registry.gitlab.com/eredinbg/soundwisecms_web:latest

deploy:
  stage: deploy
  only:
    - develop
  script:
    - sudo GITLAB_USERNAME=$GITLAB_USERNAME GITLAB_PASSWORD=$GITLAB_PASSWORD su soundwise
    - whoami
    - pwd
    - cp docker-compose.yml /home/soundwise/docker-compose.yml
    - cd /home/soundwise
    - pwd
    - docker login -u $GITLAB_USERNAME -p $GITLAB_PASSWORD registry.gitlab.com
      && docker-compose pull
      && docker-compose up -d