version: '3'

services:
  db:
    image: postgres:9.3
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
